### ISSUE TITLE
io.perbone.jejdbc.jdbc.DriverTest.testConnection failing

### ISSUE THREAD

**Issue by paradoxengine** [perbone/jejdbc#1]
Hello,
 I've started looking at this project as a lightweight way to connect to the RPM Database, but I'm not sure of its current state. I'm also trying to import it under Bazel, so it might be my attempts borked somethng. 

I seem unable to get io.perbone.jejdbc.jdbc.DriverTest.testConnection to pass, both using bazel test rules and native JUnit 4. I'm not sure this is expected (and the code is then possibly incomplete/abandoned?) or I've borked it somehow. 

Before I spend further time debugging, could you clarify what's the state?

**Comment by perbone** [comment]
Hi,
At the moment the project is stopped because I'm waiting for the final release of the new Asynchronous Database Access API (ADBA) as I think this API is more relevant for the current trend of micro services and reactive programming.
Having said that, I still plan to implement the JDBC API, but, it's not my priority at the moment. In the current state I'm afraid this project is useless for end users.

Sorry for the inconvenience.

**Comment by paradoxengine** [comment]
Thanks for the reply! It might be worth adding a note on the README about the state of the project (what you wrote is probably enough).

**Comment by perbone** [comment]
You're absolutely right I'll post a note.
Thanks
